### ISSUE TITLE
Question: Is this supported by AWS Parallel Cluster 3?

### ISSUE THREAD

**Issue by cdtiwari-ebi** [InformaticsMatters/nextflow-pcluster#1]
I am curious to know if it is supported by the latest version of AWS Parallel Cluster 3, Please let me know.
I am excited to try this in our test deployment on our use case.

**Comment by alanbchristie** [comment]
We have recently commissioned a v3 cluster and believe the instructions are essentially correct but cannot guarantee they're 100% accurate - especially as we started with a v2 cluster and it's roles and policies - which were augmented with the policies captured in thew `pcluster-v3` branch.

We have promoted the `pcluster-v3` branch to the default.

The policies for v3 are complex but we have distilled them into a simple set in the `iam` directory.

Creating the appropriate user and roles/policies and then running the `pcluster configure` command is the simplest way to start. Then modify the resultant configuration file with any customisations (specifically the `CustomActions` block).

**Comment by alanbchristie** [comment]
I've also enabled **Discussions** in this repo so we can close this and continue non-defect discussions there and reserve **Issues** for potential faults or development tasks.

Thanks for you interest, btw. I hope this repo continues to be a source of interest.

**Comment by cdtiwari-ebi** [comment]
I have tested the latest repo and found that there are two policy files(v3-user-policy.json, v3-operator-policy.json) are been created with the script of "render-policies.sh". I have used older policy json.

Documentation is missing about EFS, as a user, there are no steps covered for EFS creation with the proper VPC of parallelcluster.
